### ISSUE TITLE
Merge PR language requests

### ISSUE THREAD

**Issue by bovirus** [Tampermonkey/tampermonkey-i18n#130]
@derjanb 

Could you please merge PR here

https://github.com/Tampermonkey/tampermonkey-i18n/pulls

Could you please check issues here

https://github.com/Tampermonkey/tampermonkey-i18n/issues

Please keep the situation on github language repository updated,. 
It's importanmt.

Thanks. KR.

**Comment by derjanb** [comment]
Done.

**Comment by bovirus** [comment]
@derjanb 

Thanks.
