### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by FilipKZhong** [Tampermonkey/tampermonkey-i18n#144]
I didn't really understand how to help but I can help you in swedish translations!
You can contac me throught my youtube _Filip K Zhõng_ or throught my discord (Linked on my YouTube)! #

**Comment by derjanb** [comment]
Thanks for asking.

Simply clone this project, copy `en/messages.json` to `sv/messages.json`, translate all strings, commit the changes and create a pull request. :)

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
