### ISSUE TITLE
the userscript called "Tampermonkey translation support" doesn't work after I install it

### ISSUE THREAD

**Issue by xiaopangju** [Tampermonkey/tampermonkey-i18n#162]
Hi.
I was forked your repo `tampermonkey-i18n` and installed your userscript called `Tampermonkey translation support`.
But,I can't see the button called `Adjust to English translation` when I open the file and in the file's edit mode.
I restart my Firefox,but the userscript still doesn't work.
I am sure the userscript is _ENABLED_ .
Course of some reasons, I can't use Google Chrome to test the problem.
the vision of _Tampermonkey_ is v.4.11.6120 
the pictures of my issue:
[![rfRwTO.png](https://s3.ax1x.com/2020/12/26/rfRwTO.png)](https://imgchr.com/i/rfRwTO)

[![rfRrfH.png](https://s3.ax1x.com/2020/12/26/rfRrfH.png)](https://imgchr.com/i/rfRrfH)

[![rfWlut.png](https://s3.ax1x.com/2020/12/26/rfWlut.png)](https://imgchr.com/i/rfWlut)

[![rfWDbV.png](https://s3.ax1x.com/2020/12/26/rfWDbV.png)](https://imgchr.com/i/rfWDbV)

**Comment by shirayuki** [comment]
Here is my workaround.
![1](https://user-images.githubusercontent.com/18039/103389238-0435c900-4b51-11eb-90c7-4cc167fb5dc1.png)

**Comment by xiaopangju** [comment]
> 
> 
> Here is my workaround.
> ![1](https://user-images.githubusercontent.com/18039/103389238-0435c900-4b51-11eb-90c7-4cc167fb5dc1.png)

Maybe my Firefox is broken for user-images.githubusercontent.com, can you update this screenshot on another website(like imgchr)? Thanks!
![image](https://user-images.githubusercontent.com/56964531/103389714-7c998b80-4b4b-11eb-92e2-8ecc43aa315b.png)

**Comment by derjanb** [comment]
I've updated the gist. Thanks!
