### ISSUE TITLE
Where is the string "Deleted_on" appear?

### ISSUE THREAD

**Issue by xiaopangju** [Tampermonkey/tampermonkey-i18n#163]
Hi, Jan.
I noticed you update some text for translate, and there is a string called "Deleted_on"(LINE 454), I want to translate with context.
Can you give me a screenshot to show me where is the string appear in the Tampermonkey?
@derjanb

**Comment by derjanb** [comment]
It is used in context of a date, e.g. this script will be automatically deleted on 2020-12-31.

Thanks for updating the translations. :-)
