### ISSUE TITLE
Accessibility issue on Tampermonkey with screen readers

### ISSUE THREAD

**Issue by juliano-lopes** [Tampermonkey/tampermonkey-i18n#180]
When I try to install some script I'm not able to find the informations about it and the install button. I'm using NVDA screen reader and Jaws. Before, about 2 or 3 week ago I did it normally.
I've attached the image about that. It's a normal screen for people who are able to see, but it's impossible for blind ones.
Please, check it out to try solve this issue.
I thank you in advance.
![tampermonkey-screen-shot](https://user-images.githubusercontent.com/20558332/111677316-de3dcd80-87fd-11eb-9efe-ef0761d50dea.png)

**Comment by omerien** [comment]
Hey !
The good place to speak about that is this link : [https://github.com/Tampermonkey/tampermonkey/issues](url).
Here is the files for translation.
Thnks for reporting this bug !

**Comment by derjanb** [comment]
Closing in favor of tampermonkey/tampermonkey#1185
