### ISSUE TITLE
Bring this extension to edge

### ISSUE THREAD

**Issue by lychichem** [Tampermonkey/tampermonkey-i18n#33]
As  Microsoft introduced  [extension convert tool for edge](https://www.microsoft.com/zh-cn/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb?tduid=$c9c69b2d21266c6acf6b0f83f81e62b2$$235166$$2397989$$$$$&reportthisapp=1) today, are you interested in bringing this extension to Edge? In fact I've tested with this tool and find out just 5 errors and only one relates to core code.

**Comment by derjanb** [comment]
I already worked with an MS Edge developer and also have a TM Edge build ready. I'm just waiting for the store to allow extension uploads. :)

**Comment by Royalgamer06** [comment]
Still nothing? Is there a way to load the extension to MS Edge unofficially?

**Comment by derjanb** [comment]
It looks like Tampermonkey will be available at the Windows Store soon.

**Comment by Royalgamer06** [comment]
Great!

**Comment by derjanb** [comment]
You can now try it out:

http://tampermonkey.net/index.php?browser=edge
https://twitter.com/MSEdgeDev/status/771448889442316288

**Comment by Royalgamer06** [comment]
Awesome! Thanks!

**Comment by Royalgamer06** [comment]
Sadly importing (in any way) doesn't work.

**Comment by derjanb** [comment]
@Royalgamer06 I've published [4.2.5298](http://tampermonkey.net/changelog.php?version=4.2.5298&ext=gz80), but it might take some time until it is available. Can you please re-test with this version? MS Edge sometimes needs a little bit time to initialize TM, so please take a look at your CPU usage while testing this.

And if it's still not working, then please file a new issue here: https://github.com/Tampermonkey/tampermonkey/issues/

 Thanks.
