### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by Fahd-Harb** [Tampermonkey/tampermonkey-i18n#41]
**This great extension lack Arabic translations.
Create files for it, So that we can contribute and translate this extension to Arabic**

**Comment by derjanb** [comment]
You can do this by your own. Just clone this repository, copy the files from the English locale and start to translate them. 
I would be happy to see an Arabic translation. :)

**Comment by Fahd-Harb** [comment]
Great and Thanks, I just didn't want to add an entire new language (specially RTL one) without checking first :)
