### ISSUE TITLE
Unable to change language, always back to browser default

### ISSUE THREAD

**Issue by nigelinux** [Tampermonkey/tampermonkey-i18n#45]
I tried to change the language of Tampermonkey through its Dashboard (my browser is in Traditional Chinese). I selected English and a popup appears saying that a reload (restart?) was needed. Hitting yes will close the Dashboard but the language remains at "Browser Default" i.e. Chinese after reopening the Dashboard. I tried changing to other language but the results were the same.

**Comment by derjanb** [comment]
I've just copied it over to the Tampermonkey repo: https://github.com/Tampermonkey/tampermonkey/issues/371
