### ISSUE TITLE
Adjust to English Translation script not working

### ISSUE THREAD

**Issue by imasaru** [Tampermonkey/tampermonkey-i18n#58]
@derjanb I want to contribute to your project by translating some strings, but the userscript isn't working. I forked this repository, went to a messages.json file, and when I clicked the button, I got, "unable to determine location."

I tried in multiple browsers, multiple languages, and it still didn't work...

**Comment by derjanb** [comment]
Hi, thanks for your wish to help.
I guess you're trying this at the Japanese file [1] of your fork?
If so, then "unfortunately" the script works fine here and generates the correct output. I've copied the result to pastebin[2].

Can you please send me the URL where the issues occurs?

[1] https://github.com/imasaru/tampermonkey-i18n/blob/master/ja/messages.json
[2] https://pastebin.com/nZ4QT1gX

**Comment by imasaru** [comment]
I open the messages.json file for editing at this link: 
https://github.com/imasaru/tampermonkey-i18n/edit/master/ja/messages.json#

When I click the button, I get the same message. I just tried this on a different computer, and got the same result.

**Comment by derjanb** [comment]
Ah ok. It worked fine at this URL: https://github.com/imasaru/tampermonkey-i18n/blob/master/ja/messages.json

I've fixed the script to work at edit URLs as well.

> Also, can I just merge your messages.json from Pastebin into the ja folder on my fork, and gradually add translations?

Sure, but if you file a pull request then please make sure no dummy string (<<<string>>>) is part of the file.

Thanks.

**Comment by imasaru** [comment]
Thanks, it works now :)
