### ISSUE TITLE
Can't find the Norwegian translation in Tampermonkey

### ISSUE THREAD

**Issue by DandelionSprout** [Tampermonkey/tampermonkey-i18n#63]
Hello again. I see in the changelog for Tampermonkey 4.4 that the Norwegian translation is said to have been added to it, but I can't find it in the language settings for Tampermonkey stable for Chrome (v4.4) or for Tampermonkey Beta. So I suppose it'd be nice to double-check if the translation has really been added to Tampermonkey, I guess?

**Comment by derjanb** [comment]
Hi, while Chrome is accepting "no", "no_NO", "nb" and "nb_NO" to change the language to Norwegian, extensions need to name the folder "nb" or "nb_NO" to make Chrome use it. 😳
I've already renamed to folder via 95b91f3f9257d309e24c9413626255a7d0f841f6.
Sorry for any inconvenience.
