### ISSUE TITLE
Tampermonkey new language test

### ISSUE THREAD

**Issue by bovirus** [Tampermonkey/tampermonkey-i18n#75]
@derjanb 

How can test a new/revised GUI language before to post in GitHub?

Is it possible to add to the tampermonkey source code and option to load for test a new language for GUI?

Thanks.

**Comment by derjanb** [comment]
You can install Tampermonkey for example at Chrome, then locate your Chrome profile folder (this [FAQ entry](http://tampermonkey.net/faq.php#Q205) gives some hints) and copy the extension folder to somewhere else. You now can modify the translation of this copy and once you're done load the extension temporarily as described at [this post](https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store#answer-24577660).
