### ISSUE TITLE
Translation of Tampermonkey.net

### ISSUE THREAD

**Issue by BychekRU** [Tampermonkey/tampermonkey-i18n#76]
Hello Jan,
Sorry if this question was asked 100 times before. I didn't found any info about how can I help with translation of the site of this extension [tampermonkey.net](http://tampermonkey.net) (apply fixes and complete)?
Merry Christmas and Happy New Year!

**Comment by derjanb** [comment]
Hi, 

thanks for your help.

At the moment there is no official process (yet). The Chinese translator send some PDFs and the I've incorporated the changes into the page.
