### ISSUE TITLE
Version 4.5 - Strings untranslated

### ISSUE THREAD

**Issue by bovirus** [Tampermonkey/tampermonkey-i18n#81]
@derjanb 

In the lat build appear a window that ask for a donation.

The text inside this window is untranslated.
Please add relative strings in language file.
 
In the control panel the settings about shortkeys meaning are untranslated.
Please add relative strings in language file.

**Comment by derjanb** [comment]
> In the control panel the settings about shortkeys meaning are untranslated. Please add relative strings in language file.

Will do. Thanks.

**Comment by bovirus** [comment]
@derjanb 

Please also add the strings for donation window.
Thanks.

**Comment by zoranzoki21** [comment]
Hello @bovirus can you still reproduce this?

**Comment by bovirus** [comment]
@zoranzoki21 

Cannot reproduce now.

**Comment by zoranzoki21** [comment]
Cool! Thanks for clarification.

**Comment by zoranzoki21** [comment]
@derjanb Can you close this?
